{{- range $deployment := .Values.deployments }}
{{- range $endpoint := $deployment.endpoints }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $endpoint.name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "kergiva.labels" $ | indent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ $endpoint.container_port }}
      targetPort: "{{ $endpoint.name }}"
      protocol: {{ $endpoint.protocol }}
      name: "{{ $endpoint.name }}"
  selector:
    app.kubernetes.io/name: {{ $deployment.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}

{{- end }}
{{- end }}