---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheusbeat
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "beat.labels" . | indent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheusbeat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheusbeat
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .image.pull_secret }}
      imagePullSecrets:
        - name: {{ .image.pull_secret }}
      {{- end }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- template "security.context" }}
          image: "{{ .image.repo }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pull_policy }}
          env:
            {{ range $key, $value := .environment_variables }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            {{- range .endpoints }}
            - name: "{{ .name }}"
              containerPort: {{ .container_port }}
              protocol: {{ .protocol }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .probes.liveness.path | quote }}
              port: {{ .probes.liveness.port }}
          readinessProbe:
            httpGet:
              path: {{ .probes.readiness.path | quote }}
              port: {{ .probes.readiness.port }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          volumeMounts:
          {{- range $key, $value := .volume_mounts }}
            - name: {{ $key | quote }}
              mountPath: {{ $value | quote }}
          {{- end }}
      
    {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}

    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}