---
apiVersion: v1
kind: Service
metadata:
  name: "prometheusbeat-8080"
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "beat.labels" . | indent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - name: "https"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: "prometheusbeat-8080"
    app.kubernetes.io/instance: {{ .Release.Name }}